export const dataDigitalBestSeller = [
  {
    id: 1,
    title: "Responsive Layout",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/m/mario-kart-8-deluxe-switch/hero?_a=AJADJWI0',
  },
  {
    id: 2,
    title: "Social Media Advertising",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/t/triangle-strategy-switch/hero?_a=AJADJWI0',
  },
  {
    id: 3,
    title: "Re-branding",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/p/pokemon-legends-arceus-switch/hero?_a=AJADJWI0',
  },
  {
    id: 4,
    title: "Mobile App Development",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/s/super-mario-3d-world-plus-bowsers-fury-switch/hero?_a=AJADJWI0',
  },
  {
    id: 5,
    title: "UI / UX Design",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/c/cuphead-switch/hero?_a=AJADJWI0',
  },
];

export const packagesData = {
  webdesign: [
    {
      name: "Basic Web",
      price: 225,
      packages: [
        "1 Page Website Design",
        "HTML Based",
        "1 Banner Design",
        "Contact/Query Form",
        "3 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Startup Web",
      price: 425,
      packages: [
        "3 Page Website Design",
        "HTML Based",
        "Hover Effects",
        "2 Banner Design",
        "Sliding Banner",
        "2 Stock Photos (You can provide us more)",
        "Contact/Query Form",
        "FREE 12 Months Domain Name",
        "6 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Professional Web",
      price: 825,
      packages: [
        "Up to 5 Page Website Design",
        "3 Stock Photos (You can provide us more)",
        "3 Banner Design",
        "Sliding Banner",
        "Hover Effects",
        "Content Management System (WordPress)",
        "FREE 12 Months Domain Name",
        "Search Engine Submission",
        "Unlimited Revisions",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
        "Mobile Responsive",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Identity Web",
      price: 1425,
      packages: [
        "Unique 5 Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "5 Stock Images",
        "5 Banner Design",
        "Sliding Banner",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System (WordPress)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)",
        "FREE 12 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Elite Web",
      price: 1825,
      packages: [
        "10 Unique Page Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "Interactive Sliding Banner",
        "10 Stock Images",
        "10 Banner Design",
        "Special Hover Effects",
        "Unlimited Revisions",
        "Content Management System (WordPress or Custom)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Corporate Web",
      price: 3425,
      packages: [
        "15 to 20 Unique Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Customized WordPress & PHP Development",
        "Interactive Sliding Banner",
        "Up to 15 Custom Made Banner Designs",
        "15 Stock Images",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar",
        "Live Feeds of Social Networks integration (Optional)",
        "Mobile Responsive",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Customized Web Portal",
      price: 5855,
      packages: [
        "Complete Custom Design & Development",
        "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Unlimited Banner Designs",
        "Interactive Sliding Banner",
        "Special Hover Effects",
        "Unlimited Stock Images",
        "User Signup Area",
        "Client/User Dashboard Area",
        "Custom Coding and Development",
        "Content Management System (Custom)",
        "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Shopping Cart Integration (Optional)",
        "Complete Database Creation",
        "Signup Automated Email Authentication",
        "Web Traffic Analytics Integration",
        "3rd Party API Integrations",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar for Easy Search",
        "Live Feeds of Social Networks integration (Optional)",
        "Search Engine Submission",
        "Module-wise Architecture",
        "Extensive Admin Pane",
        "Award Winning Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "GOLDEN Customized Web",
      price: 14852,
      packages: [
        "Customized Web Portal Package Included",
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Custom Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "50 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build",
        "Responsive Web Design",
        "Account Strategy & Consultation",
        "Websites & Strategy By Industry",
        "Website Content Management",
      ],
      values: [],
    },
    {
      name: "PLATINUM Customized Web",
      price: 24702,
      packages: [
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "35 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build",
      ],
      values: [],
    },
  ],
  // second package
  logo: [
    {
      name: "Basic Logo",
      price: 45,
      packages: [
        "2 Custom Logo Design Concepts",
        "By 1 Designer",
        "1 Banner Design",
        "2 Revisions",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Startup Logo",
      price: 75,
      packages: [
        "4 Custom Logo Design Concepts",
        "By 2 Designers",
        "4 Revisions",
        "2 Banner Design",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Professional Logo",
      price: 125,
      packages: [
        "6 Logo Design Concepts",
        "By 4 Industry Based Designers",
        "6 Revisions",
        "FREE MS Electronic Letterhead (Letterhead, Business Card, Envelope)",
        "48 to 72 hours TAT",
        "FREE File Formats (EPS, Ai, GIF, JPEG, PSD)",
        "FREE 12 Months Domain Name",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Identity Logo",
      price: 175,
      packages: [
        "8 Logo Design Concepts",
        "By 5 Industry Based Designers",
        "Free Icon Design",
        "FREE Custom Stationery Design (Letterhead, Business Card, Envelope, Invoice)",
        "FREE MS Word Letterhead",
        "Email Signature Designr",
        "8 Revisions",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Corporate Logo",
      price: 225,
      packages: [
        "10 Logo Design Concepts",
        "By 6 Industry Based Designers",
        "Free Icon Design",
        "FREE Custom Stationery Design (Letterhead, Business Card, Envelope, Invoice)",
        "Double Side Flyer (OR) Bi-Fold Brochure",
        "FREE MS Electronic Letterhead",
        "Email Signature Design",
        "10 Revisions",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Elite Logo",
      price: 425,
      packages: [
        "15 Logo Design Concepts",
        "By 6 Industry Based Designers",
        "FREE Custom Stationery Design (Letterhead, Business Card, Envelope, Invoice)",
        "FREE MS Electronic Letterhead",
        "Free Icon Design",
        "3 Pages Website Design and Development",
        "10 Revisions",
        "24 to 48 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
      values: [],
    },
    {
      name: "Illustrative Logo",
      price: 329,
      packages: [
        "3 Custom Illustrative Design Concepts",
        "By 3 Industry Based Designers",
        "6 Revisions",
        "72 hours Turnaround Time",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Character Illustration",
      price: 495,
      packages: [
        "3 Custom Character Illustration",
        "By 3 Industry Based Designers",
        "6 Revisions",
        "5 Business Days Turnaround Time",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee*",
      ],
      values: [],
    },
    {
      name: "Animated Logo",
      price: 274,
      packages: [
        "2 Animated Logo Concept",
        "By 3 Industry Based Designers",
        "6 Revisions",
        "5 Business Days Turnaround Time",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
  ],
  // 3 package
  animation: [
    {
      name: "Basic Video",
      price: 325,
      packages: [
        "30 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "4 weeks Delivery",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Startup Video",
      price: 825,
      packages: [
        "60 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "5 weeks Delivery",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Professional Video",
      price: 1325,
      packages: [
        "90 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "6 weeks Delivery",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Elite Video",
      price: 2025,
      packages: [
        "120 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "Corporate Video",
      price: 2725,
      packages: [
        "180 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "3D Video Basic",
      price: 2225,
      packages: [
        "30 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "3D Video Starter",
      price: 4450,
      packages: [
        "60 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "3D Video Professional",
      price: 5450,
      packages: [
        "90 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "3D Video Elite",
      price: 6650,
      packages: [
        "90 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [],
    },
    {
      name: "GOLDEN Video Package",
      price: 14852,
      packages: [
        "3D Video Elite Included",
        "High-Quality Work & Years of Experience",
        "100% Satisfaction Guarantee",
        "100% Money-Back Guarantee",
        "Fantastic Free Customer Support after Service",
        "Unlimited FREE Revisions",
        "Professional Voice Overs � 100% Real Human Voiceovers",
        "1080P Full HD Video Quality",
        "Brand Coloring",
        "Royalty-Free Background Music",
        "Characters included",
        "Voice over recording",
        "Script writing",
        "Illustrated background included",
        "Music/sound design included",
        "Running time (seconds) 3 min",
        "High Quality Tools used",
      ],
      values: [],
    },
    {
      name: "PLATINUM Video Package",
      price: 24702,
      packages: [
        "Golden Video Included",
        "High-Quality Work & Years of Experience",
        "100% Satisfaction Guarantee",
        "100% Money-Back Guarantee",
        "Fantastic Free Customer Support after Service",
        "2 Stock Photos (You can provide us more)",
        "Unlimited FREE Revisions",
        "Professional Voice Overs � 100% Real Human Voiceovers",
        "6 Revisions",
        "1080P Full HD Video Quality",
        "Brand Coloring",
        "Royalty-Free Background Music",
        "Characters included",
        "Voice over recording",
        "Script writing",
        "Illustrated background included",
        "Music/sound design included",
        "Running time (seconds) 3 min",
        "High Quality Tools used",
      ],
      values: [],
    },
  ],
  // 4 package
  seo: [
    {
      name: "Seo Basic",
      price: 299,
      packages: [
        "5 Keywords",
        "Guaranteed Ranking on Google",
        "Off-site Optimization",
        "Link Building",
        "Social Bookmarking",
        "Basic Analytical Report",
      ],
      values: [],
    },
    {
      name: "Seo Classic",
      price: 599,
      packages: [
        "10 Keywords",
        "Guaranteed Ranking on Google",
        "Off-site Optimization",
        "On-site Optimization",
        "Link Building",
        "Social Bookmarking",
        "Comprehensive Analytical Report",
      ],
      values: [],
    },
    {
      name: "Seo Plus",
      price: 799,
      packages: [
        "20 Keywords",
        "Guaranteed Ranking on Google of relevant keywords",
        "Off-site Optimization",
        "On-site Optimization",
        "Link Building",
        "Social Bookmarking",
      ],
      values: [],
    },
    {
      name: "Seo Advance",
      price: 1499,
      packages: [
        "30 Keywords",
        "Guaranteed Ranking on Google of relevant keywords",
        "Off-site Optimization",
        "On-site Optimization",
        "Technical SEO",
        "Comprehensive Anaytics Report",
        "User friendly website",
        "Link Building",
        "Social Bookmarking",
      ],
      values: [],
    },
    {
      name: "Seo Elite",
      price: 2499,
      packages: [
        "40 Keywords",
        "Guaranteed Ranking on Google of relevant keywords",
        "Off-site Optimization",
        "On-site Optimization",
        "Technical SEO",
        "Monthly audit reports",
        "Comprehensive Analytics Report",
        "User friendly website",
        "Link Building",
        "Social Bookmarking",
        "SEO Content Support",
      ],
      values: [],
    },
  ],
  // 5 packages
  ecommerce: [
    {
      name: "E-commerce Basic",
      price: 525,
      packages: [
        "E-Commerce Website Design and Development",
        "Theme Based Design",
        "2 Banner Designs",
        "Sliding Banner",
        "3 Stock Photos",
        "06 Revisions",
        "Hover Effects",
        "Up to 10 Products",
        "Up to 3 Categories",
        "Content/Inventory Management System",
        "Easy Product Search Bar",
        "Shopping Cart Integration",
        "Payment Module Integration",
        "Direct Checkout",
        "Sign up Checkout",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "Wishlist",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "E-commerce Startup",
      price: 825,
      packages: [
        "E-Commerce Website Design and Development",
        "High-end Theme Based Design",
        "Hover Effects",
        "5 Banner Designs",
        "Sliding Banner",
        "5 Stock Photos",
        "12 Revisions",
        "Hover Effects",
        "Up to 25 Products",
        "Up to 5 Categories",
        "Content/Inventory Management System",
        "Easy Product Search Bar",
        "Shopping Cart Integration",
        "Payment Module Integration",
        "Direct Checkout",
        "Sign up Checkout",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "Wishlist",
        "Search Engine Submission",
        "Social Media Pages Integration",
        "Facebook Like Plugin integration",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "E-commerce Professional",
      price: 1325,
      packages: [
        "E-Commerce Website Design and Development",
        "Customized Theme Based Design",
        "7 Banner Designs",
        "Sliding Banner",
        "7 Stock Photos",
        "Unlimited Revisions",
        "FREE 12 Months Domain Name",
        "Search Engine Submission",
        "Unlimited Revisions",
        "Hover Effects",
        "Up to 100 Products",
        "Up to 10 Categories",
        "Content/Inventory Management System",
        "Mobile Responsive",
        "Easy Product Search Bar",
        "Shopping Cart Integration",
        "Payment Module Integration",
        "Direct Checkout",
        "Sign up Checkout",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "Wishlist",
        "Import/Export Order",
        "Bulk Import/export of Order information",
        "Search Engine Submission",
        "Wishlist",
        "SEO Friendly",
        "Web Analytics Integration",
        "Monthly Traffic Reporting",
        "Social Media Pages Integration",
        "Facebook Like Plugin integration",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "E-commerce Identity",
      price: 2525,
      packages: [
        "E-Commerce Website Design and Development",
        "Customized Tailor-Made Design",
        "Professional, Modern, Unique Design",
        "10 Banner Designs",
        "Sliding Banner",
        "10 Stock Photos",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Up to 500 Products",
        "Up to 25 Categories",
        "Product Reviews & Ratings",
        "Content/Inventory Management System",
        "Mobile Responsive",
        "User Signup Area",
        "User Sign-in Area",
        "User Dashboard Area",
        "Auto Email for Profile Validation & Notification(s)",
        "Easy Product Search Bar",
        "Shopping Cart Integration",
        "Payment Module Integration",
        "Direct Checkout",
        "Sign up Checkout",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "Wishlist",
        "Import/Export Order",
        "Bulk Import/export of Order information",
        "Search Engine Submission",
        "SEO Friendly",
        "Web Analytics Integration",
        "Monthly Traffic Reporting",
        "Social Media Pages Integration",
        "Facebook Like Plugin integration",
        "Blog page (If Required)",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "E-commerce Elite",
      price: 3525,
      packages: [
        "E-Commerce Website Design and Development",
        "Customized Tailor-Made Design",
        "Professional, Modern, Interactive, Dynamic, Unique Design",
        "User-friendly Navigation",
        "20 Banner Designs",
        "Sliding Banner",
        "20 Stock Photos",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content/Inventory Management System",
        "Mobile Responsive",
        "Unlimited Products",
        "Unlimited Categories",
        "Product Reviews & Ratings",
        "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
        "Multiple Filtrations Option",
        "Multiple Shorting Options (Newest / Price / Alphabetical / Rating)",
        "Product View with Multiple Views",
        "Product Rating",
        "Product Detail with Similar Product Range",
        "Coupon Code Generation (by category and product)",
        "Product Comparison",
        "User Signup Area",
        "User Sign-in Area",
        "User Dashboard Area",
        "Auto Email for Profile Validation & Notification(s)",
        "Last Purchase Order Details (download invoice)",
        "Customer Login / Registration via Social Login Facebook",
        "Customer profile management (From Backend and Frontend)",
        "Discounted Products Showcase",
        "New Arrival Products Showcase",
        "Discount Coupons",
        "Easy Product Search Bar",
        "Shopping Cart Integration",
        "Payment Module Integration",
        "Multiple Currency Integration",
        "Direct Checkout",
        "Sign up Checkout",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "Wishlist",
        "Import/Export Order",
        "Bulk Import/export of Order information",
        "Bulk Product Upload From Excel Sheet",
        "Export order into excel sheet",
        "Live Chat Integration",
        "Search Engine Submission",
        "SEO Friendly",
        "Web Analytics Integration",
        "Monthly Traffic Reporting",
        "Social Media Pages Integration",
        "Facebook Shop Setup",
        "Facebook Like Plugin integration",
        "Blog page (If Required)",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "E-commerce Corporate",
      price: 5525,
      packages: [
        " E-Commerce Website Design and Development",
        "Customized Tailor-Made Design",
        "Professional, Modern, Interactive, Dynamic, Unique Design",
        "User-friendly Navigation",
        "20 Banner Designs",
        "Sliding Banner",
        "20 Stock Photos",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content/Inventory Management System",
        "Mobile Responsive",
        "Unlimited Products",
        "Unlimited Categories",
        "Product Reviews & Ratings",
        "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
        "Multiple Filtrations Option",
        "Multiple Shorting Options (Newest / Price / Alphabetical / Rating)",
        "Product View with Multiple Views",
        "Product Rating",
        "Product Detail with Similar Product Range",
        "Coupon Code Generation (by category and product)",
        "Product Comparison",
        "User Signup Area",
        "User Sign-in Area",
        "User Dashboard Area",
        "Distributor / Vendor Signup Area",
        "Distributor / Vendor Sign-in Area",
        "Distributor / Vendor Dashboard Area",
        "Per sale commission from vendor",
        "Number of Product Upload (multiple packages can be created)",
        "Product Cataloguee",
        "Brand page",
        "Distributor Based Individual Store Page",
        "Distributor Track Record Management",
        "Auto Email for Profile Validation & Notification(s)",
        "Last Purchase Order Details (download invoice)",
        "Customer Login / Registration via Social Login Facebook",
        "Customer profile management (From Backend and Frontend)",
        "Discounted Products Showcase",
        "New Arrival Products Showcase",
        "Discount Coupons",
        "Easy Product Search Bar",
        "Shopping Cart Integration",
        "Payment Module Integration",
        "Cash On Delivery Option",
        "Multiple Currency Integration",
        "Direct Checkout",
        "Sign up Checkout",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "ZIP/Postal Code Checker Integration",
        "Location Wise Shipping Checker Integration",
        "Wishlist",
        "SMS Integration",
        "Email Marketing Integration",
        "Newsletter Signup Area",
        "Import/Export Order",
        "Bulk Import/export of Order information",
        "Bulk Product Upload From Excel Sheet",
        "Export Product List into Excel Sheet",
        "Export order into excel sheet",
        "Live Chat Integration",
        "Search Engine Submission",
        "SEO Friendly",
        "Web Analytics Integration",
        "Monthly Traffic Reporting",
        "Social Media Pages Integration",
        "Facebook Shop Setup",
        "Facebook Like Plugin integration",
        "Blog page (If Required)",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "GOLDEN E-commerce Corporate",
      price: 14852,
      packages: [
        " E-Commerce Corporate Package Included",
        "Customized Tailor-Made Design",
        "Professional, Modern, Interactive, Dynamic, Unique Design",
        "25 Banner Designs",
        "Sliding Banner",
        "25 Stock Photos",
        "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
        "Multiple Shorting Options (Newest / Price / Alphabetical / Rating)",
        "Product View with Multiple Views",
        "Product Rating",
        "Coupon Code Generation (by category and product)",
        "Distributor Based Individual Store Page",
        "Auto Email for Profile Validation & Notification(s)",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "ZIP/Postal Code Checker Integration",
        "Location Wise Shipping Checker Integration",
        "Wishlist",
        "SMS Integration",
        "Email Marketing Integration",
        "Newsletter Signup Area",
        "Import/Export Order",
        "Bulk Import/export of Order information",
        "Bulk Product Upload From Excel Sheet",
        "Export Product List into Excel Sheet",
        "Export order into excel sheet",
        "Live Chat Integration",
        "Search Engine Submission",
        "SEO Friendly",
        "Web Analytics Integration",
        "Monthly Traffic Reporting",
        "Social Media Pages Integration",
        "Facebook Shop Setup",
        "Facebook Like Plugin integration",
        "Blog page (If Required)",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
        "Value Added Services",
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "eCommerce Websites (Online store, woocommerce store)",
        "Portfolio site",
        "Blog and News site",
        "NGO site",
        "Personal site",
        "Mailchimp form integration",
        "Speed optimization",
        "SEO optimized secure",
        "DNS propagation",
        "Security and Backup",
        "Easy to manage or make changes on your site.",
        "Unlimited revisions ",
      ],
      values: [],
    },
    {
      name: "PLATINUM E-commerce Corporate",
      price: 24702,
      packages: [
        "Golden E-Commerce Corporate Package Included",
        "Customized Tailor-Made Design",
        "Professional, Modern, Interactive, Dynamic, Unique Design",
        "25 Banner Designs",
        "Sliding Banner",
        "25 Stock Photos",
        "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
        "Multiple Shorting Options (Newest / Price / Alphabetical / Rating)",
        "Product View with Multiple Views",
        "Product Rating",
        "Coupon Code Generation (by category and product)",
        "Distributor Based Individual Store Page",
        "Auto Email for Profile Validation & Notification(s)",
        "Tax calculator Integration",
        "Shipping calculator Integration",
        "ZIP/Postal Code Checker Integration",
        "Location Wise Shipping Checker Integration",
        "Wishlist",
        "SMS Integration",
        "Email Marketing Integration",
        "Newsletter Signup Area",
        "Import/Export Order",
        "Bulk Import/export of Order information",
        "Bulk Product Upload From Excel Sheet",
        "Export Product List into Excel Sheet",
        "Export order into excel sheet",
        "Live Chat Integration",
        "Search Engine Submission",
        "SEO Friendly",
        "Web Analytics Integration",
        "Monthly Traffic Reporting",
        "Social Media Pages Integration",
        "Facebook Shop Setup",
        "Facebook Like Plugin integration",
        "Blog page (If Required)",
        "Sitemap",
        "Complete W3C Validation",
        "Dedicated Team of Designers and Developers",
        "Complete Deployment",
        "Value Added Services",
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "eCommerce Websites (Online store, woocommerce store)",
        "Portfolio site",
        "Blog and News site",
        "NGO site",
        "Personal site",
        "Mailchimp form integration",
        "Speed optimization",
        "SEO optimized secure",
        "DNS propagation",
        "Security and Backup",
        "Easy to manage or make changes on your site.",
        "Unlimited revisions",
        "Will deliver Quality eCommerce store with 100% satisfaction",
        "Fully tested and bug free wordpress website",
        "Payment gateway integration (Stripe, Paypal or WooCommerce Payments)",
        "Functional website ultimately",
        "Number of pages 30",
        "Plugins/extensions installation unlimited",
      ],
      values: [],
    },
    
  ],
  // 6 package

  social: [
    {
      name: "Social Identity",
      price: 149,
      packages: [
        "Social Business Accounts Creation (any 3 networks)",
        "Cover Photo Design",
        "Welcome Page Design",
        "Profile Picture Design",
        "2 Cover Photo Design",
        "3 Custom Posts",
      ],
      values: [],
    },
    {
      name: "Basic Monthly",
      price: 499,
      packages: [
        "2 Postings per week, per network (Facebook, Instagram)",
        "Content Creation",
        "Social Page Optimization",
        "Social Media Strategy",
        "Monthly Progress Report",
        "Facebook/Instagram Likes Campaign [+$100]",
        "Paid Boosting (additional charges as per the budget)",
      ],
      values: [],
    },
    {
      name: "Standard Monthly",
      price: 899,
      packages: [
        "5 Postings per week, per network (Facebook, Instagram)",
        "Social Page Optimization",
        "Social Media Strategy",
        "Comment Moderation",
        "Spam Monitoring",
        "Reputation Management",
        "Monthly Progress Report",
        "Facebook/Instagram Likes Campaign [+$100]",
        "Paid Boosting (additional charges as per the budget)",
      ],
      values: [],
    },
    {
      name: "Advanced Monthly",
      price: 1299,
      packages: [
        "6 Postings per week, per network (Facebook, Instagram)",
        "Content Creation",
        "Social Account Setup",
        "Social Page Optimization",
        "Business Page Optimization",
        "Banners and Profile Pics",
        "Social Media Strategy",
        "Facebook/Instagram Likes Campaign ($100 Campaign)",
        "Comment Moderation",
        "Spam Monitoring",
      ],
      values: [],
    },
    {
      name: "Social Elite",
      price: 3600,
      packages: [
        "Choose From Facebook, Twitter, Instagram",
        "30 Posts Per Month",
        "12 Custom Images",
        "6 Boosted Posts",
        "$600 Ad Spend Required",
        "Social Media Strategy",
        "Social Media Audit",
        "Social Recommendations",
        "Brand Analysis",
        "Dedicated Project Manager",
        "Facebook/Instagram Likes ( $200 Campaign )",
        "Daily Monitoring of Social Assets",
        "Daily Monitoring of Boosted Posts",
        "24 Hours Customer Response Time",
        "Social Media Setup",
        "Social Media Configuration",
        "Profile Photos And Banners",
        "Paid Boosting (additional charges as per the budget)",
      ],
      values: [],
    },
    {
      name: "Social Enterprise",
      price: 5700,
      packages: [
        "Choose From Facebook, Twitter & Instagram",
        "40 Posts Per Month",
        "16 Custom Images",
        "8 Boosted Posts",
        "$800 Ad Spend Required",
        "Social Media Strategy",
        "Social Media Audit",
        "Social Recommendations",
        "Brand Analysis",
        "Dedicated Project Manager",
        "Daily Monitoring of Social Assets",
        "Daily Monitoring of Boosted Posts",
        "24 Hours Customer Response Time",
        "Social Media Setup",
        "Social Media Configuration",
        "Profile Photos And Banners",
        "Facebook / Instagram($400 Campaign)",
        "Paid Boosting (additional charges as per the budget)",
      ],
      values: [],
    },
    {
      name: "Golden Social Enterprise",
      price: 14852,
      packages: [
        "Social Enterprise Package Included",
        "social Account Creartion",
        "Social Account Audit And manatgement (Facebook ,LinkdIn , Instagarfam , Twitter )",
        "Number of Posts (Content creation And design management )",
        "Gif Creation",
        "Monthly Content Calendar",
        "SMM Startegy Building",
        "CLients Approval Per Post",
        "Posts sharing And Hash Tagging",
        "Monthly Achievements Reporting",
        "Fb And Insta Adds Campaign Mangement Charges",
        "Client advertisment Budget Per day",
        "Add Spending And Archiement Reports will be shared",
        "Animated Video (Without voice Over And Script )",
        "Cover Photo Design",
        "Profile Picture Design",
        "6 Cover Photo Design",
        "3 Custom Posts",
      ],
      values: [],
    },
    {
      name: "Platinum Social Enterprise",
      price: 24702,
      packages: [
        "Golden Enterprise Package Included",
        "social Account Creartion",
        "Social Account Audit And manatgement (Facebook ,LinkdIn , Instagarfam , Twitter )",
        "Number of Posts (Content creation And design management )",
        "Gif Creation",
        "Monthly Content Calendar",
        "SMM Startegy Building",
        "CLients Approval Per Post",
        "Posts sharing And Hash Tagging",
        "Monthly Achievements Reporting",
        "Fb And Insta Adds Campaign Mangement Charges",
        "Client advertisment Budget Per day",
        "Add Spending And Archiement Reports will be shared",
        "Animated Video (Without voice Over And Script )",
        "Cover Photo Design",
        "Profile Picture Design",
        "9 Cover Photo Design",
        "5 Custom Posts",
        "Customization options",
        "Personalized strategies",
        "Transparent reporting",
        "Routine consultations",
        "Account setup and optimization",
        "Upfront prices",
      ],
      values: [],
    },
  ],
};
