export const dataDigitalBestSeller = [
  {
    id: 1,
    title: "Responsive Layout",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/m/mario-kart-8-deluxe-switch/hero?_a=AJADJWI0',
  },
  {
    id: 2,
    title: "Social Media Advertising",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/t/triangle-strategy-switch/hero?_a=AJADJWI0',
  },
  {
    id: 3,
    title: "Re-branding",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/p/pokemon-legends-arceus-switch/hero?_a=AJADJWI0',
  },
  {
    id: 4,
    title: "Mobile App Development",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/s/super-mario-3d-world-plus-bowsers-fury-switch/hero?_a=AJADJWI0',
  },
  {
    id: 5,
    title: "UI / UX Design",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis nihil, labore tenetur voluptates sequi veniam adipisci ea ex vero repellat ullam quo at ad possimus soluta fugiat a animi vitae.",
    // linkImg:
    //   'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/c/cuphead-switch/hero?_a=AJADJWI0',
  },
];

export const packagesData = {
  webdesign: [
    {
      name: "Basic Web",
      price: 225,
      packages: [
        "1 Page Website Design",
        "HTML Based",
        "1 Banner Design",
        "Contact/Query Form",
        "3 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Startup Web",
      price: 425,
      packages: [
        "3 Page Website Design",
        "HTML Based",
        "Hover Effects",
        "2 Banner Design",
        "Sliding Banner",
        "2 Stock Photos (You can provide us more)",
        "Contact/Query Form",
        "FREE 12 Months Domain Name",
        "6 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Professional Web",
      price: 825,
      packages: [
        "Up to 5 Page Website Design",
        "3 Stock Photos (You can provide us more)",
        "3 Banner Design",
        "Sliding Banner",
        "Hover Effects",
        "Content Management System (WordPress)",
        "FREE 12 Months Domain Name",
        "Search Engine Submission",
        "Unlimited Revisions",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
        "Mobile Responsive",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Identity Web",
      price: 1425,
      packages: [
        "Unique 5 Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "5 Stock Images",
        "5 Banner Design",
        "Sliding Banner",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System (WordPress)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)",
        "FREE 12 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Elite Web",
      price: 1825,
      packages: [
        "10 Unique Page Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "Interactive Sliding Banner",
        "10 Stock Images",
        "10 Banner Design",
        "Special Hover Effects",
        "Unlimited Revisions",
        "Content Management System (WordPress or Custom)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Corporate Web",
      price: 3425,
      packages: [
        "15 to 20 Unique Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Customized WordPress & PHP Development",
        "Interactive Sliding Banner",
        "Up to 15 Custom Made Banner Designs",
        "15 Stock Images",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar",
        "Live Feeds of Social Networks integration (Optional)",
        "Mobile Responsive",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Customized Web Portal",
      price: 5855,
      packages: [
        "Complete Custom Design & Development",
        "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Unlimited Banner Designs",
        "Interactive Sliding Banner",
        "Special Hover Effects",
        "Unlimited Stock Images",
        "User Signup Area",
        "Client/User Dashboard Area",
        "Custom Coding and Development",
        "Content Management System (Custom)",
        "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Shopping Cart Integration (Optional)",
        "Complete Database Creation",
        "Signup Automated Email Authentication",
        "Web Traffic Analytics Integration",
        "3rd Party API Integrations",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar for Easy Search",
        "Live Feeds of Social Networks integration (Optional)",
        "Search Engine Submission",
        "Module-wise Architecture",
        "Extensive Admin Pane",
        "Award Winning Team of Expert Designers and Developers",
         "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "GOLDEN Customized Web",
      price: 14852,
      packages: [
        "Customized Web Portal Package Included",
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Custom Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "50 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build",
        "Responsive Web Design",
        "Account Strategy & Consultation",
        "Websites & Strategy By Industry",
        "Website Content Management",
      ],
      values: [
    
      ],
    },
    {
      name: "PLATINUM Customized Web",
      price: 24702,
      packages: [
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "35 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build"
      ],
      values: [
    
      ],
    },
  ],
  // second package
  magento: [
    {
      name: "Basic Logo",
      price: 45,
      packages: [
        "2 Custom Logo Design Concepts",
        "By 1 Designer",
        "1 Banner Design",
        "2 Revisions",
        "3 Revisions",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Startup Logo",
      price: 75,
      packages: [
        "4 Custom Logo Design Concepts",
        "By 2 Designers",
        "4 Revisions",
        "2 Banner Design",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      
      ],
      values: [
      ],
    },
    {
      name: "Professional Logo",
      price: 125,
      packages: [
        "6 Logo Design Concepts",
        "By 4 Industry Based Designers",
        "6 Revisions",
        "FREE MS Electronic Letterhead (Letterhead, Business Card, Envelope)",
        "48 to 72 hours TAT",
        "FREE File Formats (EPS, Ai, GIF, JPEG, PSD)",
        "FREE 12 Months Domain Name",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Identity Logo",
      price: 175,
      packages: [
        "8 Logo Design Concepts",
        "By 5 Industry Based Designers",
        "Free Icon Design",
        "FREE Custom Stationery Design (Letterhead, Business Card, Envelope, Invoice)",
        "FREE MS Word Letterhead",
        "Email Signature Designr",
        "8 Revisions",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Corporate Logo",
      price: 225,
      packages: [
        "10 Logo Design Concepts",
        "By 6 Industry Based Designers",
        "Free Icon Design",
        "FREE Custom Stationery Design (Letterhead, Business Card, Envelope, Invoice)",
        "Double Side Flyer (OR) Bi-Fold Brochure",
        "FREE MS Electronic Letterhead",
        "Email Signature Design",
        "10 Revisions",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
       
      ],
      values: [
    
      ],
    },
    {
      name: "Elite Logo",
      price: 425,
      packages: [
        "15 Logo Design Concepts",
        "By 6 Industry Based Designers",
        "FREE Custom Stationery Design (Letterhead, Business Card, Envelope, Invoice)",
        "FREE MS Electronic Letterhead",
        "Free Icon Design",
        "3 Pages Website Design and Development",
        "10 Revisions",
        "24 to 48 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Illustrative Logo",
      price: 329,
      packages: [
        "3 Custom Illustrative Design Concepts",
        "By 3 Industry Based Designers",
        "6 Revisions",
        "72 hours Turnaround Time",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        
      ],
      values: [
       
      ],
    },
    {
      name: "Character Illustration",
      price: 495,
      packages: [
        "3 Custom Character Illustration",
        "By 3 Industry Based Designers",
        "6 Revisions",
        "5 Business Days Turnaround Time",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee*"
      ],
      values: [
    
      ],
    },
    {
      name: "Animated Logo",
      price: 274,
      packages: [
        "2 Animated Logo Concept",
        "By 3 Industry Based Designers",
        "6 Revisions",
        "5 Business Days Turnaround Time",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
    
      ],
    },
  ],
  // 3 package
  animation: [
    {
      name: "Basic Video",
      price: 325,
      packages: [
        "30 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "4 weeks Delivery",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Startup Video",
      price: 825,
      packages: [
        "60 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "5 weeks Delivery",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Professional Video",
      price: 1325,
      packages: [
        "90 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "6 weeks Delivery",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
      ],
    },
    {
      name: "Elite Video",
      price: 2025,
      packages: [
        "120 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
       
      ],
      values: [
      ],
    },
    {
      name: "Corporate Video",
      price: 2725,
      packages: [
        "180 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
      ],
      values: [
       
      ],
    },
    {
      name: "3D Video Basic",
      price: 2225,
      packages: [
        "30 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
        
      ],
      values: [
      ],
    },
    {
      name: "3D Video Starter",
      price: 4450,
      packages: [
        "60 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
        
      ],
      values: [
       
      ],
    },
    {
      name: "3D Video Professional",
      price: 5450,
      packages: [
        "90 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
        
      ],
      values: [
    
      ],
    },
    {
      name: "3D Video Elite",
      price: 6650,
      packages: [
        "90 Second Video",
        "Professional Script",
        "Custom Design",
        "Storyboard",
        "Custom Animation",
        "Voice Over & Sound Effects",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "100% Unique Design Guarantee",
        
      ],
      values: [
    
      ],
    },
    {
      name: "GOLDEN Video Package",
      price: 14852,
      packages: [
        "3D Video Elite Included",
        "High-Quality Work & Years of Experience",
        "100% Satisfaction Guarantee",
        "100% Money-Back Guarantee",
        "Fantastic Free Customer Support after Service",
        "Unlimited FREE Revisions",
        "Professional Voice Overs � 100% Real Human Voiceovers",
        "1080P Full HD Video Quality",
        "Brand Coloring",
        "Royalty-Free Background Music",
        "Characters included",
        "Voice over recording",
        "Script writing",
        "Illustrated background included",
        "Music/sound design included",
        "Running time (seconds) 3 min",
        "High Quality Tools used",
      ],
      values: [
      ],
    },
    {
      name: "PLATINUM Video Package",
      price: 24702,
      packages: [
        "Golden Video Included",
        "High-Quality Work & Years of Experience",
        "100% Satisfaction Guarantee",
        "100% Money-Back Guarantee",
        "Fantastic Free Customer Support after Service",
        "2 Stock Photos (You can provide us more)",
        "Unlimited FREE Revisions",
        "Professional Voice Overs � 100% Real Human Voiceovers",
        "6 Revisions",
        "1080P Full HD Video Quality",
        "Brand Coloring",
        "Royalty-Free Background Music",
        "Characters included",
        "Voice over recording",
        "Script writing",
        "Illustrated background included",
        "Music/sound design included",
        "Running time (seconds) 3 min",
        "High Quality Tools used",
      ],
      values: [
      ],
    },
  ],
  // 4 package
  seo: [
    {
      name: "Seo Basic",
      price: 299,
      packages: [
        "5 Keywords",
        "Guaranteed Ranking on Google",
        "Off-site Optimization",
        "Link Building",
        "Social Bookmarking",
        "Basic Analytical Report",
        
      ],
      values: [
      ],
    },
    {
      name: "Seo Classic",
      price: 599,
      packages: [
        "10 Keywords",
        "Guaranteed Ranking on Google",
        "Off-site Optimization",
        "On-site Optimization",
        "Link Building",
        "Social Bookmarking",
        "Comprehensive Analytical Report",
      ],
      values: [
 
      ],
    },
    {
      name: "Seo Plus",
      price: 799,
      packages: [
        "20 Keywords",
        "Guaranteed Ranking on Google of relevant keywords",
        "Off-site Optimization",
        "On-site Optimization",
        "Link Building",
        "Social Bookmarking",
      ],
      values: [
      ],
    },
    {
      name: "Seo Advance",
      price: 1499,
      packages: [
        "30 Keywords",
        "Guaranteed Ranking on Google of relevant keywords",
        "Off-site Optimization",
        "On-site Optimization",
        "Technical SEO",
        "Comprehensive Anaytics Report",
        "User friendly website",
        "Link Building",
        "Social Bookmarking",
      ],
      values: [
      ],
    },
    {
      name: "Seo Elite",
      price: 2499,
      packages: [
        "40 Keywords",
        "Guaranteed Ranking on Google of relevant keywords",
        "Off-site Optimization",
        "On-site Optimization",
        "Technical SEO",
        "Monthly audit reports",
        "Comprehensive Analytics Report",
        "User friendly website",
        "Link Building",
        "Social Bookmarking",
        "SEO Content Support",
      ],
      values: [
      ],
    },
    {
      name: "Corporate Web",
      price: 3425,
      packages: [
        "15 to 20 Unique Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Customized WordPress & PHP Development",
        "Interactive Sliding Banner",
        "Up to 15 Custom Made Banner Designs",
        "15 Stock Images",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar",
        "Live Feeds of Social Networks integration (Optional)",
        "Mobile Responsive",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Customized Web Portal",
      price: 5855,
      packages: [
        "Complete Custom Design & Development",
        "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Unlimited Banner Designs",
        "Interactive Sliding Banner",
        "Special Hover Effects",
        "Unlimited Stock Images",
        "User Signup Area",
        "Client/User Dashboard Area",
        "Custom Coding and Development",
        "Content Management System (Custom)",
        "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Shopping Cart Integration (Optional)",
        "Complete Database Creation",
        "Signup Automated Email Authentication",
        "Web Traffic Analytics Integration",
        "3rd Party API Integrations",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar for Easy Search",
        "Live Feeds of Social Networks integration (Optional)",
        "Search Engine Submission",
        "Module-wise Architecture",
        "Extensive Admin Pane",
        "Award Winning Team of Expert Designers and Developers",
         "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "GOLDEN Customized Web",
      price: 14852,
      packages: [
        "Customized Web Portal Package Included",
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Custom Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "50 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build",
        "Responsive Web Design",
        "Account Strategy & Consultation",
        "Websites & Strategy By Industry",
        "Website Content Management",
      ],
      values: [
    
      ],
    },
    {
      name: "PLATINUM Customized Web",
      price: 24702,
      packages: [
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "35 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build"
      ],
      values: [
    
      ],
    },
  ],
  // 5 packages
  ecommerce: [
    {
      name: "Basic Web",
      price: 225,
      packages: [
        "1 Page Website Design",
        "HTML Based",
        "1 Banner Design",
        "Contact/Query Form",
        "3 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Startup Web",
      price: 425,
      packages: [
        "3 Page Website Design",
        "HTML Based",
        "Hover Effects",
        "2 Banner Design",
        "Sliding Banner",
        "2 Stock Photos (You can provide us more)",
        "Contact/Query Form",
        "FREE 12 Months Domain Name",
        "6 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Professional Web",
      price: 825,
      packages: [
        "Up to 5 Page Website Design",
        "3 Stock Photos (You can provide us more)",
        "3 Banner Design",
        "Sliding Banner",
        "Hover Effects",
        "Content Management System (WordPress)",
        "FREE 12 Months Domain Name",
        "Search Engine Submission",
        "Unlimited Revisions",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
        "Mobile Responsive",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Identity Web",
      price: 1425,
      packages: [
        "Unique 5 Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "5 Stock Images",
        "5 Banner Design",
        "Sliding Banner",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System (WordPress)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)",
        "FREE 12 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Elite Web",
      price: 1825,
      packages: [
        "10 Unique Page Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "Interactive Sliding Banner",
        "10 Stock Images",
        "10 Banner Design",
        "Special Hover Effects",
        "Unlimited Revisions",
        "Content Management System (WordPress or Custom)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Corporate Web",
      price: 3425,
      packages: [
        "15 to 20 Unique Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Customized WordPress & PHP Development",
        "Interactive Sliding Banner",
        "Up to 15 Custom Made Banner Designs",
        "15 Stock Images",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar",
        "Live Feeds of Social Networks integration (Optional)",
        "Mobile Responsive",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Customized Web Portal",
      price: 5855,
      packages: [
        "Complete Custom Design & Development",
        "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Unlimited Banner Designs",
        "Interactive Sliding Banner",
        "Special Hover Effects",
        "Unlimited Stock Images",
        "User Signup Area",
        "Client/User Dashboard Area",
        "Custom Coding and Development",
        "Content Management System (Custom)",
        "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Shopping Cart Integration (Optional)",
        "Complete Database Creation",
        "Signup Automated Email Authentication",
        "Web Traffic Analytics Integration",
        "3rd Party API Integrations",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar for Easy Search",
        "Live Feeds of Social Networks integration (Optional)",
        "Search Engine Submission",
        "Module-wise Architecture",
        "Extensive Admin Pane",
        "Award Winning Team of Expert Designers and Developers",
         "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "GOLDEN Customized Web",
      price: 14852,
      packages: [
        "Customized Web Portal Package Included",
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Custom Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "50 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build",
        "Responsive Web Design",
        "Account Strategy & Consultation",
        "Websites & Strategy By Industry",
        "Website Content Management",
      ],
      values: [
    
      ],
    },
    {
      name: "PLATINUM Customized Web",
      price: 24702,
      packages: [
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "35 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build"
      ],
      values: [
    
      ],
    },
  ],
  // 6 package
  shopify: [
    {
      name: "Basic Web",
      price: 225,
      packages: [
        "1 Page Website Design",
        "HTML Based",
        "1 Banner Design",
        "Contact/Query Form",
        "3 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Startup Web",
      price: 425,
      packages: [
        "3 Page Website Design",
        "HTML Based",
        "Hover Effects",
        "2 Banner Design",
        "Sliding Banner",
        "2 Stock Photos (You can provide us more)",
        "Contact/Query Form",
        "FREE 12 Months Domain Name",
        "6 Revisions",
        "Complete W3C Certified HTML",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Professional Web",
      price: 825,
      packages: [
        "Up to 5 Page Website Design",
        "3 Stock Photos (You can provide us more)",
        "3 Banner Design",
        "Sliding Banner",
        "Hover Effects",
        "Content Management System (WordPress)",
        "FREE 12 Months Domain Name",
        "Search Engine Submission",
        "Unlimited Revisions",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
        "Mobile Responsive",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Identity Web",
      price: 1425,
      packages: [
        "Up to 5 Page Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "5 Stock Images",
        "5 Banner Design",
        "Sliding Banner",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System (WordPress)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)",
        "FREE 12 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Elite Web",
      price: 1825,
      packages: [
        "10 Unique Page Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Custom WordPress Development",
        "Interactive Sliding Banner",
        "10 Stock Images",
        "10 Banner Design",
        "Special Hover Effects",
        "Unlimited Revisions",
        "Content Management System (WordPress or Custom)",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Corporate Web",
      price: 3425,
      packages: [
        "15 to 20 Unique Pages Website Design",
        "Custom, Interactive, Dynamic & High End Web Design",
        "Customized WordPress & PHP Development",
        "Interactive Sliding Banner",
        "Up to 15 Custom Made Banner Designs",
        "15 Stock Images",
        "Unlimited Revisions",
        "Special Hover Effects",
        "Content Management System",
        "Mobile Responsive",
        "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar",
        "Live Feeds of Social Networks integration (Optional)",
        "Mobile Responsive",
        "FREE 24 Months Domain Name",
        "Google Friendly Sitemap",
        "Search Engine Submission",
        "Complete W3C Certified HTML",
        "Industry specified Team of Expert Designers and Developers",
        "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "Customized Web Portal",
      price: 5855,
      packages: [
        "Complete Custom Design & Development",
        "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Unlimited Banner Designs",
        "Interactive Sliding Banner",
        "Special Hover Effects",
        "Unlimited Stock Images",
        "User Signup Area",
        "Client/User Dashboard Area",
        "Custom Coding and Development",
        "Content Management System (Custom)",
        "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
        "Online Payment Integration (Optional)",
        "Multi Lingual (Optional)",
        "Custom Dynamic Forms (Optional)",
        "Shopping Cart Integration (Optional)",
        "Complete Database Creation",
        "Signup Automated Email Authentication",
        "Web Traffic Analytics Integration",
        "3rd Party API Integrations",
        "Signup Area (For Newsletters, Offers etc.)",
        "Search Bar for Easy Search",
        "Live Feeds of Social Networks integration (Optional)",
        "Search Engine Submission",
        "Module-wise Architecture",
        "Extensive Admin Pane",
        "Award Winning Team of Expert Designers and Developers",
         "Complete Deployment",
      ],
      values: [
        "Complete Source Files",
        "Dedicated Project Manager",
        "100% Ownership Rights",
        "100% Satisfaction Guarantee",
        "100% Money Back Guarantee",
        "*NO MONTHLY OR ANY HIDDEN FEE*",
      ],
    },
    {
      name: "GOLDEN Customized Web",
      price: 14852,
      packages: [
        "Customized Web Portal Package Included",
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Custom Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "50 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build",
        "Responsive Web Design",
        "Account Strategy & Consultation",
        "Websites & Strategy By Industry",
        "Website Content Management",
      ],
      values: [
    
      ],
    },
    {
      name: "PLATINUM Customized Web",
      price: 24702,
      packages: [
        "Gold Customize Design & Development",
        "Crypto Based Portal, Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
        "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
        "Interactive Sliding Banner",
        "Golden aspect ratio Logo",
        "Client/User/Admin Dashboard Area",
        "Unique Design",
        "Content Writting",
        "Search Engine Optimization",
        "Databases On advanced Technologies",
        "Complete Deployment",
        "3rd Party API Integrations",
        "Special Hover Effects",
        "35 Revisions",
        "Social Paltforms",
        "User Friendly",
        "Integrations",
        "Light Weight Build"
      ],
      values: [
    
      ],
    },
  ],
};
